export const environment = {
  production: true,
  liveDebug: false,
  adsIsTesting: false,
  projName: "RealEstateNews",
  homeTitle: "Real Estate Investing Today",
  host: "realestenews.com",
  keyword: "real_estate_investing",
  subject: "real estate investing",
  apiUrl: "https://api.realestenews.com",
  adMobIdAndroidBanner: "ca-app-pub-2578395398126606/5377480230",
  adMobIdAndroidInterstitial: "ca-app-pub-2578395398126606/8330946636",
  adMobIdiOSBanner: "",
  adMobIdiOSInterstitial: "",
  googleAppID: "",
  GoogleProjNumber: "",
  iapOptions: "location=no,hardwareback=no,toolbar=n,zoom=no",
  iapTarget: "_blank",
  minSpeakText: 20,
}
